# Default values for lakefs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: treeverse/lakefs
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  ingressClassName: ""
  defaultBackend: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


podAnnotations: {}
jobPodAnnotations:
  sidecar.istio.io/inject: "false"

deployment:
  port: 8000

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

s3Fallback:
  enabled: false

# yamllint disable rule:comments

# Example: using node instance storage for caching committed data:
# For more information: https://www.vipmind.me/infra/aws/how-to-use-ephemeral-disk-from-ec2-instance-in-eks.html
#committedLocalCacheVolume:
#  hostPath:
#    path: /media/ephemeral0

# yamllint enable

serviceAccount: {}

# Extra Environment Values - allows yaml definitions
extraEnvVars:
#  - name: VALUE_FROM_SECRET
#    valueFrom:
#      secretKeyRef:
#        name: secret_name
#        key: secret_key


secrets:
  databaseConnectionString: ""
  authEncryptSecretKey: ""
  

lakefsConfig: |

  
  database:
    type: postgres

  blockstore:
    type: s3
    s3:
      force_path_style: true
      endpoint:  https://nyc3.digitaloceanspaces.com
      discover_bucket_region: false
      credentials:
        access_key_id: DO00DVPL7G2KH694LMTT
        secret_access_key: zxiRQgitV6EqToqafVcxrEDW7Ce29oEsCC+zvN0rEC0
